///This file is automatically generated. DO NOT EDIT, all your changes would be lost.
class Assets {
  Assets._();

  static const String imagesAppIcon = 'assets/images/app_icon.png';
  static const String imagesAppleIcon = 'assets/images/apple_icon.svg';
  static const String imagesFacebookIcon = 'assets/images/facebook_icon.svg';
  static const String imagesGoogleIcon = 'assets/images/google_icon.svg';
  static const String imagesLogo = 'assets/images/logo.svg';
  static const String imagesPageViewItem1BackgroundImage =
      'assets/images/page_view_item1_background_image.svg';
  static const String imagesPageViewItem1Image =
      'assets/images/page_view_item1_image.svg';
  static const String imagesPageViewItem2BackgroundImage =
      'assets/images/page_view_item2_background_image.svg';
  static const String imagesPageViewItem2Image =
      'assets/images/page_view_item2_image.svg';
  static const String imagesPlant = 'assets/images/plant.svg';
  static const String imagesSplashBottom = 'assets/images/splash_bottom.svg';
  static const String imagesCheck = 'assets/images/check.svg';
  static const String imagesEdit = 'assets/images/edit.svg';
  static const String imagesFeaturedItemBackground =
      'assets/images/featured_item_background.svg';
  static const String imagesFilter = 'assets/images/filter.svg';
  static const String imagesFilter2 = 'assets/images/filter2.svg';
  static const String imagesLocation = 'assets/images/location.svg';
  static const String imagesNotification = 'assets/images/notification.svg';
  static const String imagesProfileImage = 'assets/images/profile_image.png';
  static const String imagesSearchIcon = 'assets/images/search_icon.svg';
  static const String imagesTrash = 'assets/images/trash.svg';
  static const String imagesVector = 'assets/images/Vector.svg';
  static const String imagesWatermelonTest =
      'assets/images/watermelon_test.png';
  static const String imagesHomeBold = 'assets/images/home_bold.svg';
  static const String imagesHomeOutline = 'assets/images/home_outline.svg';
  static const String imagesProductsBold = 'assets/images/products_bold.svg';
  static const String imagesProductsOutline =
      'assets/images/products_outline.svg';
  static const String imagesShoppingCartBold =
      'assets/images/shopping_cart_bold.svg';
  static const String imagesShoppingCartOutline =
      'assets/images/shopping_cart_outline.svg';
  static const String imagesUserBold = 'assets/images/user_bold.svg';
  static const String imagesUserOutline = 'assets/images/user_outline.svg';
}
