const kSubabaseUrl = 'https://nwmgxqxazyjtzzcvwixh.supabase.co';
const kSubabaseApiKey =
    'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im53bWd4cXhhenlqdHp6Y3Z3aXhoIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc2MzAzMTE2MCwiZXhwIjoyMDc4NjA3MTYwfQ.SS-39XdBtLmrt493U-KjwCYpXI-OuRRo10DrsOyVhkk';
