// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD52BCiz_pe3-p78iO_vF5gzU2rVd_FXuc',
    appId: '1:717167524481:web:94435c4036bece40d4eb80',
    messagingSenderId: '717167524481',
    projectId: 'fruit-hub-11510',
    authDomain: 'fruit-hub-11510.firebaseapp.com',
    storageBucket: 'fruit-hub-11510.firebasestorage.app',
    measurementId: 'G-E59T9XZCCP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhhcKhzdv8y7S79ElpPdGe2k0ulqDOpr8',
    appId: '1:717167524481:android:79b91958f73841b2d4eb80',
    messagingSenderId: '717167524481',
    projectId: 'fruit-hub-11510',
    storageBucket: 'fruit-hub-11510.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZj4HVcPvExRdVAC6z-hs0aLvIYHAj4HA',
    appId: '1:717167524481:ios:36ff6fe6b5f72f54d4eb80',
    messagingSenderId: '717167524481',
    projectId: 'fruit-hub-11510',
    storageBucket: 'fruit-hub-11510.firebasestorage.app',
    androidClientId: '717167524481-93jqsrd7qks0dbd2r8lu9cc7ej9653ed.apps.googleusercontent.com',
    iosClientId: '717167524481-gnsidh4rjdt9mmjibt1vk7mk7mts2grt.apps.googleusercontent.com',
    iosBundleId: 'com.example.fruitsHubDashboard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZj4HVcPvExRdVAC6z-hs0aLvIYHAj4HA',
    appId: '1:717167524481:ios:36ff6fe6b5f72f54d4eb80',
    messagingSenderId: '717167524481',
    projectId: 'fruit-hub-11510',
    storageBucket: 'fruit-hub-11510.firebasestorage.app',
    androidClientId: '717167524481-93jqsrd7qks0dbd2r8lu9cc7ej9653ed.apps.googleusercontent.com',
    iosClientId: '717167524481-gnsidh4rjdt9mmjibt1vk7mk7mts2grt.apps.googleusercontent.com',
    iosBundleId: 'com.example.fruitsHubDashboard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD52BCiz_pe3-p78iO_vF5gzU2rVd_FXuc',
    appId: '1:717167524481:web:7a92895bda0e3921d4eb80',
    messagingSenderId: '717167524481',
    projectId: 'fruit-hub-11510',
    authDomain: 'fruit-hub-11510.firebaseapp.com',
    storageBucket: 'fruit-hub-11510.firebasestorage.app',
    measurementId: 'G-KHJGQLMCMH',
  );
}
